security:
  oauth2:
    client:
      registration:
        google:
          clientId: 714045881492-ovr3iv6voi2ok36bskr91qk96qf0ulj4.apps.googleusercontent.com
          clientSecret: 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
          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000